spring:
  application:
    name: course-api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: course-repository
          uri: lb://COURSE-REPOSITORY
          predicates:
          - Path=/course/**
server:
  port: 8089
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: false
    fetchRegistry: true
